/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Classes.*;
import Exceções.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author helio
 */
public class TelaInicio extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicio
     */
    
    ArrayList<Personagem> personagens= new ArrayList<Personagem>();
    ArrayList<Personagem> inimigo= new ArrayList<Personagem>();
	Inumano inumanos;
	Humano humanos;
        Inumano inumanosI;
	Humano humanosI;
	static int aux = 0;
        
    /* criando as armas*/
	Arma garraLetal = new Arma("Garra Letal",200);
	Arma tridenteSagrado = new Arma("Tridente Sagrado",320);
	Arma espadaBarroca = new Arma("Espada Barroca",400);
	Arma porrete = new Arma("Porrete",280);
	Arma cajado = new Arma("Cajado",100);
	Arma besta = new Arma("Besta",320);
	Arma esferaDeAtaque = new Arma("Esfera de Ataque",300);
	//-------------------------
	
	/* criando as magias*/
	Magia pocaoDeVida = new Magia("Pocao de Vida",0,200,12);
	Magia halitoDeFogo = new Magia("Halito de Fogo",400,0,12);
	Magia bioAntraz = new Magia("Bio Antraz",360,0,14);
	Magia cura = new Magia("Cura",0,400,16);
	Magia flamaGelada = new Magia("Flama Gelada",320,0,14);
	Magia envenenamento = new Magia("Envenenamento",280,0,12);
	Magia tempestade = new Magia("Tempestade",200,0,12);
	//----------------------------
        
        
    public TelaInicio() {
        initComponents();
        //this.setLocationRelativeTo(null);
        //this.getMinimumSize();
        //setExtendedState(MAXIMIZED_BOTH);//abrir a janela em tamanho maximo.
        //jLabel1.setSize();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CheckBox_Guerreiro = new javax.swing.JCheckBox();
        CheckBox_Mago = new javax.swing.JCheckBox();
        CheckBox_Ladrão = new javax.swing.JCheckBox();
        CheckBox_Paladino = new javax.swing.JCheckBox();
        CheckBox_Animal = new javax.swing.JCheckBox();
        CheckBox_Dragão = new javax.swing.JCheckBox();
        CheckBox_Troll = new javax.swing.JCheckBox();
        CheckBox_Zumbi = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 580));
        getContentPane().setLayout(null);

        CheckBox_Guerreiro.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox_Guerreiro.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox_Guerreiro.setText("Guerreiro");
        CheckBox_Guerreiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_GuerreiroActionPerformed(evt);
            }
        });
        getContentPane().add(CheckBox_Guerreiro);
        CheckBox_Guerreiro.setBounds(820, 320, 110, 23);

        CheckBox_Mago.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox_Mago.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox_Mago.setText("Mago");
        CheckBox_Mago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_MagoActionPerformed(evt);
            }
        });
        getContentPane().add(CheckBox_Mago);
        CheckBox_Mago.setBounds(40, 330, 120, 23);

        CheckBox_Ladrão.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox_Ladrão.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox_Ladrão.setText("Ladrão");
        CheckBox_Ladrão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_LadrãoActionPerformed(evt);
            }
        });
        getContentPane().add(CheckBox_Ladrão);
        CheckBox_Ladrão.setBounds(240, 320, 140, 23);

        CheckBox_Paladino.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox_Paladino.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox_Paladino.setText("Paladino");
        CheckBox_Paladino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_PaladinoActionPerformed(evt);
            }
        });
        getContentPane().add(CheckBox_Paladino);
        CheckBox_Paladino.setBounds(510, 330, 150, 23);

        CheckBox_Animal.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox_Animal.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox_Animal.setText("Animal");
        CheckBox_Animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_AnimalActionPerformed(evt);
            }
        });
        getContentPane().add(CheckBox_Animal);
        CheckBox_Animal.setBounds(240, 50, 140, 23);

        CheckBox_Dragão.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox_Dragão.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox_Dragão.setText("Dragão");
        CheckBox_Dragão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_DragãoActionPerformed(evt);
            }
        });
        getContentPane().add(CheckBox_Dragão);
        CheckBox_Dragão.setBounds(810, 40, 90, 23);

        CheckBox_Troll.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox_Troll.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox_Troll.setText("Troll");
        CheckBox_Troll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_TrollActionPerformed(evt);
            }
        });
        getContentPane().add(CheckBox_Troll);
        CheckBox_Troll.setBounds(510, 50, 130, 23);

        CheckBox_Zumbi.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox_Zumbi.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox_Zumbi.setText("Zumbi");
        CheckBox_Zumbi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_ZumbiActionPerformed(evt);
            }
        });
        getContentPane().add(CheckBox_Zumbi);
        CheckBox_Zumbi.setBounds(50, 50, 110, 20);

        jButton1.setText("Começar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 480, 450, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/giphy (2).gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 230, 480, 320);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 90, 34, 14);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/giphy (2).gif"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 430, 300);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/giphy (2).gif"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(510, 0, 480, 320);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/giphy (2).gif"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(510, 250, 480, 320);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/giphy (2).gif"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 240, 480, 320);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/giphy (2).gif"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(520, 90, 370, 220);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/giphy (2).gif"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(260, 220, 480, 320);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/giphy (2).gif"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(440, 0, 480, 320);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/giphy (2).gif"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 0, 430, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckBox_TrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_TrollActionPerformed
       if (CheckBox_Troll.isSelected()) {
					aux += 1;
					if(aux>1){
						desmarcarCaixaSelecao();
					}else{
						inumanos = new Inumano(2800,20,100,20,cajado,"Troll");
						personagens.add(inumanos);
					}
				} else {
					aux -= 1;
				}
    }//GEN-LAST:event_CheckBox_TrollActionPerformed

    private void CheckBox_GuerreiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_GuerreiroActionPerformed
        if (CheckBox_Guerreiro.isSelected()) {
					aux += 1;
					if(aux>1){
						desmarcarCaixaSelecao();
					}else{
						humanos = new Humano(4000,30,80,20,porrete,"Guerreiro");
						personagens.add(humanos);
					}
				} else {
					aux -= 1;
				}
    }//GEN-LAST:event_CheckBox_GuerreiroActionPerformed

    private void CheckBox_PaladinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_PaladinoActionPerformed
        if (CheckBox_Paladino.isSelected()) {
					aux += 1;
					if(aux>1){
						desmarcarCaixaSelecao();
					}else{
						humanos = new Humano(3200,80,60,60,besta,"Paladino");
						personagens.add(humanos);
					}
				} else {
					aux -= 1;
				}
    }//GEN-LAST:event_CheckBox_PaladinoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaUmPlayer tup = new TelaUmPlayer();
				
				try{
				if(aux==1){
					setVisible(false);
					if(CheckBox_Zumbi.isSelected() || CheckBox_Troll.isSelected() || CheckBox_Animal.isSelected() ||CheckBox_Dragão.isSelected()){
						arrayInimigo();
                                                tup.daInicio(inumanos, inimigo);
                                                tup.setVisible(true);
					}else if(CheckBox_Ladrão.isSelected() || CheckBox_Guerreiro.isSelected() || CheckBox_Mago.isSelected() ||CheckBox_Paladino.isSelected()){
						arrayInimigo();
                                                tup.daInicio(humanos, inimigo);
						tup.setVisible(true);
					}
				}else {
					throw new ErroNaoTerEscolhidoPersonagem (1);//esta lan�ando a exception
				}
				}catch(ErroNaoTerEscolhidoPersonagem e){
					JOptionPane.showMessageDialog(null, e);//esta pegando a exception
				}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CheckBox_LadrãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_LadrãoActionPerformed
        if (CheckBox_Ladrão.isSelected()) {
					aux += 1;
					if(aux>1){
						desmarcarCaixaSelecao();
					}else{
						humanos = new Humano(2800,50,40,50,cajado,"Ladrão");
						personagens.add(humanos);
					}
				} else {
					aux -= 1;
				}
    }//GEN-LAST:event_CheckBox_LadrãoActionPerformed

    private void CheckBox_MagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_MagoActionPerformed
        if (CheckBox_Mago.isSelected()) {
					aux += 1;
					if(aux>1){
						desmarcarCaixaSelecao();
					}else{
						humanos = new Humano(2500,100,30,100,cajado,"Mago");
						personagens.add(humanos);
					}
				} else {
					aux -= 1;
				}
    }//GEN-LAST:event_CheckBox_MagoActionPerformed

    private void CheckBox_DragãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_DragãoActionPerformed
       if (CheckBox_Dragão.isSelected()) {
					aux += 1;
					if(aux>1){
						desmarcarCaixaSelecao();
					}else{
						inumanos = new Inumano(3000,40,100,50,garraLetal,"Dragão");
						personagens.add(inumanos);
                                                
					}
				} else {
					aux -= 1;
				}
    }//GEN-LAST:event_CheckBox_DragãoActionPerformed

    private void CheckBox_AnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_AnimalActionPerformed
        if (CheckBox_Animal.isSelected()) {
					aux += 1;
					if(aux>1){
						desmarcarCaixaSelecao();
					}else{
					inumanos = new Inumano(3200,30,90,20,garraLetal,"Animal");
					personagens.add(inumanos);
					}
				} else {
					aux -= 1;
					
				}
    }//GEN-LAST:event_CheckBox_AnimalActionPerformed

    private void CheckBox_ZumbiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_ZumbiActionPerformed
        if (CheckBox_Zumbi.isSelected()) {
					aux += 1;
					if(aux>1){
						desmarcarCaixaSelecao();
					}else{
						inumanos = new Inumano(2500,20,80,90,cajado,"Zumbi");
						personagens.add(inumanos);
					}
				} else {
					aux -= 1;
				}
    }//GEN-LAST:event_CheckBox_ZumbiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicio().setVisible(true);
            }
        });
    }
    
    public void desmarcarCaixaSelecao() {
		JOptionPane.showMessageDialog(null, "VOCê DEVE ESCOLHER UM PERSONAGEM!!!!");
		CheckBox_Guerreiro.setSelected(false);
		CheckBox_Ladrão.setSelected(false);
		CheckBox_Mago.setSelected(false);
		CheckBox_Paladino.setSelected(false);
		CheckBox_Dragão.setSelected(false);
		CheckBox_Troll.setSelected(false);
		CheckBox_Animal.setSelected(false);
		CheckBox_Zumbi.setSelected(false);
		aux = 0;
	}
	//------------FIM METODO Desmarcar Caixa de Sele��o
	
	public void desabilitaCaixaSeleção() {
		CheckBox_Guerreiro.setEnabled(false);
		CheckBox_Ladrão.setEnabled(false);
		CheckBox_Mago.setEnabled(false);
		CheckBox_Paladino.setEnabled(false);
		CheckBox_Dragão.setEnabled(false);
		CheckBox_Troll.setEnabled(false);
		CheckBox_Animal.setEnabled(false);
		CheckBox_Zumbi.setEnabled(false);
	}

        public void arrayInimigo(){
            inumanosI = new Inumano(2500,20,80,90,cajado,"Zumbi");
            inimigo.add(inumanosI);
            inumanosI = new Inumano(3200,30,90,20,garraLetal,"Animal");
            inimigo.add(inumanosI);
            inumanosI = new Inumano(3000,40,100,50,garraLetal,"Dragão");
            inimigo.add(inumanosI);
            inumanosI = new Inumano(2800,20,100,20,cajado,"Troll");
            inimigo.add(inumanosI);
            humanosI = new Humano(2500,100,30,100,cajado,"Mago");
            inimigo.add(humanosI);
            humanosI = new Humano(2800,50,40,50,cajado,"Ladrão");
            inimigo.add(humanosI);
            humanosI = new Humano(4000,30,80,20,porrete,"Guerreiro");
            inimigo.add(humanosI);
            humanosI = new Humano(3200,80,60,60,besta,"Paladino");
            inimigo.add(humanosI);
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox_Animal;
    private javax.swing.JCheckBox CheckBox_Dragão;
    private javax.swing.JCheckBox CheckBox_Guerreiro;
    private javax.swing.JCheckBox CheckBox_Ladrão;
    private javax.swing.JCheckBox CheckBox_Mago;
    private javax.swing.JCheckBox CheckBox_Paladino;
    private javax.swing.JCheckBox CheckBox_Troll;
    private javax.swing.JCheckBox CheckBox_Zumbi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
